### ISSUE TITLE
Empty package?

### ISSUE THREAD

**Issue by StevenLangbroek** [rogerballard/nestjs-relay#131]
**Describe the bug**
I've tried installing nestjs-relay through `yarn` and `npm`, but in both cases the `dist` folder appears to be missing?

![image](https://user-images.githubusercontent.com/296796/92002646-5e0fb900-ed40-11ea-9b51-88071eb2101a.png)

I've tried versions 3.0.1 through 3.0.5, all with the same result...

**To Reproduce**
- `nest new app`
- `yarn add graphql-relay nestjs-relay`
- `import { } from 'nestjs-relay';`

![image](https://user-images.githubusercontent.com/296796/92002931-b5ae2480-ed40-11ea-860f-679bbb4eed38.png)

**Expected behavior**
Files should probably be there :D

If there's anything I can do to help debug I'd love to hear it. Thanks <3

**Comment by rogerballard** [comment]
Thanks for raising - I'll take a look 👍

**Comment by StevenLangbroek** [comment]
Just FYI, yarn's registry seems to agree: https://yarnpkg.com/package/nestjs-relay?files

**Comment by rogerballard** [comment]
@StevenLangbroek I have resolved this in [v4.0.0](https://github.com/rogerballard/nestjs-relay/releases/tag/v4.0.0) and tested with npm. The `/dist` directory is back in yarn's registry. 

Could you confirm that this has fixed the issue in your project please?
